name: Daily Run

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Explicitly use Python 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install pygooglenews ignoring its pinned feedparser
          pip install pygooglenews==0.1.2 --no-deps --no-input
          # Forcibly install feedparser==6.0.0 
          # (works fine on Python 3.9, even though pygooglenews says <6)
          pip install feedparser==6.0.0
          # Install everything else from requirements.txt
          pip install -r requirements.txt

      - name: Run main.py
        run: python main.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated update of news articles"
          git push origin main
