name: Daily Run

on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression runs the job every day at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow from the GitHub interface

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygooglenews==0.1.2 --no-deps
        pip install feedparser==6.0.0
        pip install -r requirements.txt

    - name: Run main.py
      run: |
        python main.py

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m "Automated update of news articles"
        git push
